### ISSUE TITLE
Abstrakt er ikke brukt - vet ikke om det er mening

### ISSUE THREAD

**Issue by yonyonson** [Informasjonsforvaltning/modelldcat-ap-no#107]
Hei!

Leser forslag til spekken og liker den veldig godt. Det jeg lurer på er: er dt med vilje at dere bruker ikke `abstract` som stereoptype på klasser?

For at om vi skal lese modellen bokstavelig, er det mulig å opprette masse objeketer av klasse `modelldcatno:ModelElement`, og det er ikke meningen (om jeg tolker det korrekt). Dere vil at folk skal opprette heller `modelldcatno:DataType`, `modelldcatno:ObjectType` andre klasser som arver fra `modelldcatno:ModelElement`, men ikke selve `modelldcatno:ModelElement`.

Mvh,
Petr Vasilev
Arkivverket

**Comment by jimjyang** [comment]
Fiksa (#112 og #113)
