### ISSUE TITLE
Assosiasjoner fra Attribute er ikke gjensidig utelukkende

### ISSUE THREAD

**Issue by yonyonson** [Informasjonsforvaltning/modelldcat-ap-no#108]
Hei!

Jeg ser at assosiasjoner fra `modelldcatno:Attribute` klasse til klasser `modelldcatno:ObjectType`, `modelldcatno: SimpleType`, `modelldcatno:DataType` og `modelldcatno:CodeList` er ikke gjensidig utelukkende. Er det begrensning av notasjon eller meningen?...

For at er det mulig å definere attributt som inneholder både objekttype, datatype, enkelttype og kodeliste, og jeg er i tvil om det er det som dere vil.

Jeg vet også at det erikke så lett å modellere dette med UML (ref https://stackoverflow.com/questions/1719035/how-to-model-mutually-exclusive-attributes-in-uml ), så det er mulig at dere utelat dette med vilje.

Petr

**Comment by jimjyang** [comment]
Fiksa (#112)
