### ISSUE TITLE
Spørsmål: Relasjon til metamodell i prosjekt "Deling av data"

### ISSUE THREAD

**Issue by yonyonson** [Informasjonsforvaltning/modelldcat-ap-no#109]
Hei!

Det er heller et spørsmål enn bug med modellen. Hva er forhold mellom ModellDCAT-AP-NO og arbeidet som gjøres i prosjektet "Deling av data" med metamodell?

Jeg sjekker det også internt hos oss.

Mvh,
Petr

**Comment by tafjord** [comment]
Hei! Vi satte igang en arbeidsgruppe: "felles tilnærming til informajsonsmodeller" i fjor høst. Denne spesifikasjonen er en leveranse fra denne arbeidsgruppen. Var det det du tenkte på?

**Comment by yonyonson** [comment]
Jeg visste ikke hva var forholdet mellom de to (denne spekken og prosjektet "Deling av data", som jeg vet flere fra oss deltar i), derfor spurte jeg :)

Så arbeidsgruppa  "Felles tilnærming til informajsonsmodeller" er en del av prosjketet "Deling av data", forsto jeg det riktig?..

**Comment by jimjyang** [comment]
@yonyonson Arbeidsgruppen er ikke en del av prosjektet "Deling av data", men en del av linjeoppgaven (informasjonsforvaltning) til Digdir. Arbeidsgruppens leveranser understøtter målsetningen for "Deling av data" ved bl.a. å muliggjøre deling av informasjonsmodeller, kodelister osv.

**Comment by jimjyang** [comment]
Siden det ikke er mer diskusjon, oppfølgingskommentar/-spørsmål eller lignende, velger jeg å lukke dette Issuet.
