### ISSUE TITLE
Modelldcatno:Realization mangler

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#135]
Klassen mangler både i beskrivelsen av klassene og i UML-modellene. modelldcatno:Specialization har fått en av egenskapene til modelldcatno:Realization, modelldcatno:hasSupllier. Dette må rettes opp i spesifikasjonen og UML-modellen.

Endringer er lagt inn word-dokument.

**Comment by jimjyang** [comment]
Fiksa
