### ISSUE TITLE
Klasser og egenskaper som mangler referanser

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#143]
En del egendefinerte klasser og egenskaper mangler referanser.
Er også meldt inn i regnarket med høringsinnspill.

**Comment by tafjord** [comment]
Er ikke dette referanse tilbake til seg selv, altså spesifikasjonen? Eller skal det lenkes til turtle-fila? Hvis vi lenker denne url-en https://data.norge.no/vocabulary/modelldcatno#Association   går en til https://data.norge.no/vocabulary/modelldcatno/modelldcatno.ttl. @ToHelland @jimjyang

**Comment by tafjord** [comment]
Litt kjapp på avtrekkeren muligens over. Ser at vi ikke lenker URI-er når det er "egne". Fjerner forøvrig referanse-feltet (jmf annet issue) og kun har URI-feltet....
