### ISSUE TITLE
Klassen modelldcatno:Association mangler egenskap

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#150]
Klassen skal ha egenskapen modelldcatno:references med status anbefalt og multiplisitet 0..1.  Egenskapen er en subegenskap av modelldcatno:hasType og har range ModelElement. Ved en feil ble denne ikke med i høringsutkastet til spesifikasjonen.

Er meldt inn i word-arket med endringer.

**Comment by jimjyang** [comment]
Fiksa
