### ISSUE TITLE
UML-modell - dct:Standard som superklasse til modelldcatno:InformationModel

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#153]
Modellere inn dct:Standard som superklasse til modelldcatno:InformationModel i UML-modellen.

**Comment by ToHelland** [comment]
Vi legger ikke dette inn i UML-modellen da det kompliserer modellen noe. Forholdet beskrives i tabellene i spesifikasjonen.

**Comment by jimjyang** [comment]
Beskrevet i spesifikasjonen nå.
