### ISSUE TITLE
Aktør (foaf:Agent) - tekst

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#159]
Legge inn følgende tekst under Aktør (egenskaper pr klasse, samme som for DCAT-AP-NO): "Klassen Aktør er obligatorisk. Det anbefales at URI til Aktør (foaf:Agent) er identisk med den URI som Enhetsregisteret (Brønnøysundregistrene) har på enheten/virksomheten dersom den finnes i registeret, f.eks. dct:publisher <https://data.brreg.no/enhetsregisteret/api/enheter/974760673>."

**Comment by jimjyang** [comment]
Fiksa
