### ISSUE TITLE
Manglende mellomrom i egenskapsnavn i spesifikasjonen

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#160]
Norsk term for modelldcatno:modelElementBelongsToModul, skal skrives tilhører modul, ikke tilhørerModul.

NB! URI'en kan bli endret, avhengig av om det går gjennom høringsmøtet for ModellDCAT-AP-NO.

Meldt inn i regnark. URI er endret til modelldcatno:belongsToModul.

**Comment by jimjyang** [comment]
Fiksa.
