### ISSUE TITLE
Legge til nye navnerom

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#161]
Følgende navnerom må legges til kapittelet "URIer" som er i bruk:
 rdf:  http://www.w3.org/1999/02/22-rdf-syntax-ns#
xkos: https://rdf-vocabulary.ddialliance.org/xkos/

**Comment by jimjyang** [comment]
> xkos: https://rdf-vocabulary.ddialliance.org/xkos/

Lenken gir 404, bruker denne isteden: https://ddialliance.org/Specification/XKOS/1.2/OWL/xkos.html

**Comment by jimjyang** [comment]
Fiksa
