### ISSUE TITLE
Fjerne mellomrom mellom prefiks og term i URI'er (spesifikasjon)

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#165]
En del av URI'ene i klassebeskrivelsene (URI-feltet) og egenskaper (URI- og Range-feltene) er det mellomrom etter ':' i prefiksen.

F.eks.
modelldcatno: SimpleType, skal skrives modelldcatno:SimpleType

**Comment by jimjyang** [comment]
Fiksa
