### ISSUE TITLE
Publisering av ontologien modelldcatno i maskinlesbart format

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/modelldcat-ap-no#169]

**Comment by stigbd** [comment]
Er det master eller review-versjonen som skal publiserast til data.norge.no/vocabulary ?

**Comment by jimjyang** [comment]
Ja, fra master.

**Comment by stigbd** [comment]
Implementert publiseringsløype og bestilt publisering på https://data.norge.no/vocabulary/modelldcatno

**Comment by jimjyang** [comment]
Fiksa
