### ISSUE TITLE
Range og domain på egenskaper for klassen modelldcatno:CodeElement må endres (OWL)

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#171]
Klassen Code heter nå CodeElement

Følgende egenskaper skal hadomain og range: modelldcatno:CodeElement

###  https://rdf-vocabulary.ddialliance.org/xkos/next
xkos:next rdf:type owl:ObjectProperty ;
          **rdfs:domain skos:Concept ;
          rdfs:range skos:Concept** .

###  https://rdf-vocabulary.ddialliance.org/xkos/previous
xkos:previous rdf:type owl:ObjectProperty ;
              **rdfs:domain skos:Concept ;
              rdfs:range skos:Concept .**

Følgende egenskaper skal ha range modelldcatno:CodeList og domain modelldcat:CodeElement:
###  http://www.w3.org/2004/02/skos/core#inScheme
skos:inScheme rdf:type owl:ObjectProperty ;
              **rdfs:range skos:ConceptScheme .**

###  http://www.w3.org/2004/02/skos/core#topConceptOf
skos:topConceptOf rdf:type owl:ObjectProperty ;
                  **rdfs:domain skos:Concept ;
                  rdfs:range skos:ConceptScheme .**

**Comment by tormodv** [comment]
Siden vi egentlig henter skos:konstruksjoner over til våre klasser, så la jeg det inn som en del av klassedefinisjonen. Det dekker egentlig i praksis det samme. Vil vi ha begge deler?

> ###  https://data.norge.no/vocabulary/modelldcatno#CodeElement
modelldcatno:CodeElement rdf:type owl:Class ;
                         rdfs:subClassOf [ rdf:type owl:Restriction ;
                                           owl:onProperty skos:inScheme ;
                                           owl:someValuesFrom modelldcatno:CodeList
                                         ] ,
                                         [ rdf:type owl:Restriction ;
                                           owl:onProperty skos:topConceptOf ;
                                           owl:someValuesFrom modelldcatno:CodeList
                                         ] ,
                                         [ rdf:type owl:Restriction ;
                                           owl:onProperty xkos:next ;
                                           owl:someValuesFrom modelldcatno:CodeElement
                                         ] ,
                                         [ rdf:type owl:Restriction ;
                                           owl:onProperty xkos:previous ;
                                           owl:someValuesFrom modelldcatno:CodeElement
                                         ] ,
                                         [ rdf:type owl:Restriction ;
                                           owl:onProperty skos:notation ;
                                           owl:someValuesFrom rdfs:Literal
                                         ] ;
                         rdfs:label "Code Element"@en ,
                                    "Kodeelement"@nb .

[ rdf:type owl:Axiom ;
   owl:annotatedSource modelldcatno:CodeElement ;
   owl:annotatedProperty rdfs:subClassOf ;
   owl:annotatedTarget [ rdf:type owl:Restriction ;
                         owl:onProperty skos:notation ;
                         owl:someValuesFrom rdfs:Literal
                       ] ;
   rdfs:comment "Kodens verdi/identifikator"@nb
 ] .

**Comment by jimjyang** [comment]
Tormod har rett i at vi på møtet 24/9 konkluderte med å fjerne skos:Concept og skos:ConceptScheme fra spesifikasjonen/modellen, og bruker de relevante skos- og xkos-egenskapene direkte på våre egendefinerte klasser (modelldcatno:CodeList og modelldcatno:CodeElement). Domain og Range skal derfor ikke lenger være skos-klassene men våre egne klasser. 

Ang. #178, @tormodv, det skal være skos:topConceptOf istf. skos:hasTopConcept på linje 181 (domain og range der ser riktig ut).
