### ISSUE TITLE
foaf:agent

### ISSUE THREAD

**Issue by tormodv** [Informasjonsforvaltning/modelldcat-ap-no#19]
Har en utgivertype, burde kanskje bare være type, siden den brukes som range for creator også.

**Comment by tafjord** [comment]
Tror jeg @jimjyang mener noe om :)

**Comment by jimjyang** [comment]
Hvis det er type utgiver, så er et dct:type med range skos:Concept, jf. [Aktør:utgivertype i DCAT-AP-NO](https://informasjonsforvaltning.github.io/dcat-ap-no/#aktor-utgivertype).

**Comment by jimjyang** [comment]
... dessuten med obligatorisk bruk av [ADMS publisher type vocabulary](https://informasjonsforvaltning.github.io/dcat-ap-no/#_for_egenskapen_dcttype).

**Comment by tormodv** [comment]
Da kommer den i en riktigere utgave
