### ISSUE TITLE
Valideringsregler manglar

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/modelldcat-ap-no#232]
Vi må få på plass valideringsregler som vi kan bruke til å maskinelt validere modell-katalogarl. I første omgang er det nok å etablere reglar som sjekkar obligatoriske egenskaper. Reglane må implementerast som SHACL shapes.

Sjå t.d. https://github.com/Informasjonsforvaltning/dcat-ap-no/ for korleis dette kan løysast.

**Comment by ToHelland** [comment]
Støtter den, har vært en fordel for modelleierne også. Pr i dag er det mye arbeid å avdekke hva som er feil eller mangler når høstingen feiler.

**Comment by stigbd** [comment]
Og validator er snart på plass, så her mangler kun shacl-grafen. Fiksar du, @ToHelland ?

**Comment by ToHelland** [comment]
Ja, du tenker på å lage filen med shacl-valideringen?

**Comment by jimjyang** [comment]
Jeg holder på med.

**Comment by jimjyang** [comment]
SHACL-filen er etablert og under (løpende) utvikling/oppdatering. Issuet lukkes.
