### ISSUE TITLE
Endre status og multiplisitet til skos:notation og skos:prefLabel i klassen modelldcatno:CodeElement

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#233]
skos:notation skal være obligatorisk, mens skos:prefLabel skal være anbefalt - motsatt av det de er i dag. 
skos:notation 0..1 --> 1..1
skos:prefLabel 1..n --> 0..n
Må oppdateres i spesifikasjonsteksten og UML-modellen.

**Comment by jimjyang** [comment]
Fiksa.
