### ISSUE TITLE
Endre status til egenskapen dct:description i klassen modelldcatapno:InformationsModell

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#236]
Foreslår å endre denne fra "obligatorisk" til "anbefalt" og multiplisitet fra 1..n til 0..n. Det er ikke alle som har beskrivelse knyttet til modellene i modelleringsverktøyene sine. Det kan skape en del utfordringer med høstingen hvis dette skal være obligatorisk. Bør prioritere å få høstet modellene nå i første omgang. 

Må endres både i spesifikasjonsteksten og UML-modellen.

**Comment by jimjyang** [comment]
Fiksa.
