### ISSUE TITLE
Ny egenskap for klassen modelldcatno:Property, modelldcatno:navigable

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#238]
Skal inn i ModellDCAT-AP-NO V1.1
OWL:

###  https://data.norge.no/vocabulary/modelldcatno#navigable
modelldcatno:navigable rdf:type owl:DatatypeProperty ;
                       rdfs:domain modelldcatno:Property ;
                       rdfs:range xsd:boolean ;
                       rdfs:label "navigable"@en ,
                                  "navigerbar"@nb .

Norsk term: Navigerbar
Status: Anbefalt
Multiplisitet: 0..1.

Må beskrives i spesifikasjonstekst og UML-modell.

Begrunnelse: Bedre for å kunne beskrive assosiasjoner med ulike retninger.

**Comment by jimjyang** [comment]
Fiksa
