### ISSUE TITLE
Ny egenskap, modelldcatno:constraint, for klassene modelldcatno:ModelElement og modelldcatno:Property

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#239]
Egenskap for å kunne høste constraints/begrensning.
Skal inn i ModellDCAT-AP-NO V1.1
OWL:

###  https://data.norge.no/vocabulary/modelldcatno#constraint
modelldcatno:constraint rdf:type owl:ObjectProperty ;
                        rdfs:domain [ rdf:type owl:Class ;
                                      owl:unionOf ( modelldcatno:ModelElement
                                                    modelldcatno:Property
                                                  )
                                    ] ;
                        rdfs:range modelldcatno:Property ;
                        rdfs:label "begrensning"@nb ,
                                   "constraint"@en .

I tillegg er det definert to subtyper:
###  https://data.norge.no/vocabulary/modelldcatno#or
modelldcatno:or rdf:type owl:ObjectProperty ;
                rdfs:subPropertyOf modelldcatno:constraint ;
                rdfs:label "eller"@nb ,
                           "or"@en .

###  https://data.norge.no/vocabulary/modelldcatno#xor
modelldcatno:xor rdf:type owl:ObjectProperty ;
                 rdfs:subPropertyOf modelldcatno:constraint ;
                 rdf:type owl:SymmetricProperty ;
                 rdfs:label "enten eller"@nb ,
                            "xor"@en .

Norsk term: begrensning
Multiplisitet: 0..*
Status: Valgfri

Må beskrives i spesifikasjonstekst og UML-modell.

**Comment by jimjyang** [comment]
Fiksa
