### ISSUE TITLE
Utvide multiplisitet for modelldcatno:belongsToModule

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#241]
Et modellelement kan grupperes i flere moduler. Denne endres derfor fra 0..1 til 0..*.

Gjelder for klassen modelldcatno:ModelElement og  modelldcatno:Property.

Må oppdateres i spesifikasjonsteksten og UML-modellen.

**Comment by jimjyang** [comment]
Fiksa.
