### ISSUE TITLE
dct:conformsTo som ny egenskap på modelldcatno:informationModel

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#242]
dct:conformsTo legges inn som egenskap på modelldcatno:informationModel.

Multiplisitet:0..n
Range: dct:Standard
Norsk term: i samsvar med
Status: Valgfri

Skal være en del av 1.1-versjonen. Må legges inn i tekst og tegnes inn i UML-modell.

**Comment by jimjyang** [comment]
Fiksa
