### ISSUE TITLE
Skrivefeil Egenskap: tilhører modul (modelldcatnobelongsToModule)

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#278]
I beskrivelsen av egenskapen står det: Brukes til å referere til en modellmodul/delmodell som **modellen** inngår i.

Det skal stå: Brukes til å referere til en modellmodul/delmodell som egenskapen inngår i.

**Comment by jimjyang** [comment]
Fiksa
