### ISSUE TITLE
Behov for utvidelser i ModellDCAT-AP-NO.

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#295]
Se siste kapittel, "Nye og endrede egenskaper": https://teams.microsoft.com/l/file/C17E4331-3D4A-4479-A23F-932BD0BD11F6?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FNye%20egenskaper%20versjon%201.0%20til%201.1.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3

Gjelder:
nye/endrede egenskaper:

- min/maxExclusive for Enkeltype (modelldcatno:SimpleType)
- utvidet range for modelldcatno:hasSupplier i klassen Realisering (modelldcatno:Realization)
- utvidet range for egenskapen er abstraksjon av (modelldcatno:isAbstractionOf) i klassen Abstraksjon (modelldcatno:Abstraction)

Se også forslag til endringslogg (rød skrift):  https://teams.microsoft.com/l/file/0E6689AC-2151-4CB4-929E-89442E484EBC?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FEndringslogg%20v1.0%20til%20v.1.1.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3

**Comment by jimjyang** [comment]
Fiksa
