### ISSUE TITLE
Note vs Constraint

### ISSUE THREAD

**Issue by tormodv** [Informasjonsforvaltning/modelldcat-ap-no#321]
I forbindelse med oppdateringen av note, så har vi fått en liten språkutfordring

Note til ting heter annotates.
ConstraintRule til ting heter constraint.

Det hadde vært bedre å bruke verbformen her, constraints og på norsk begrenser. Jeg tror det er lov å skrive det uten s-en til slutt, men det føles bedre med.

**Comment by ToHelland** [comment]
Støtter den. Noe innspill @jimjyang?

**Comment by jimjyang** [comment]
Enig å bruke verbformen og med s.

**Comment by jimjyang** [comment]
forresten, constrains uten t.
