### ISSUE TITLE
Egenskaper for klassen modelldcatno:Attribute skal være gjensidig utelukkende

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#329]
I dag er egenskapene gjensidig utelukkende med unntak av modelldcatno:hasValueFrom og hasSimpleType, som kan opptre samtidig for en Attributt. Dette er ment for å kunne spesifisere formatet til en kode. Slik det er modellert, kan dette lett misforstås. Gjør derfor alle egenskapene til Attributt-klassen gjensidig utelukkende.

Tekst i informasjonsboks under egenskaper for klassen Attributt, må endres: https://data.norge.no/specification/modelldcat-ap-no/#Attributt-egenskaper
Skal stå følgende tekst:
"Egenskapene til modelldcatno:Attribute er gjensidig utelukkende, dvs. at de ikke kan forekomme samtidig." 

Dette må vel også påpekes i endringsloggen?

**Comment by jimjyang** [comment]
> Dette må vel også påpekes i endringsloggen?

Ja, skal nevnes i endringsloggen også.
