### ISSUE TITLE
Erstatte egenskapen modelldcatno:CodeListReference med rdfs:seeAlso for modelldcatno:CodeList

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#349]
Egenskapen modelldcatno:CodeListReference  fjernes og erstattes med rdfs:seeAlso med range rdfs:Resource.

Følgende må gjøres:
OWL-oppdateres
Spesifikasjon oppdateres
UML-modell oppdateres

**Comment by jimjyang** [comment]
Fiksa
