### ISSUE TITLE
Publisering - filnavnet for PDF-filen som kan lastes ned

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/modelldcat-ap-no#351]
Det er ønskelig at filnavnet for PDF-versjonen som kan lastes ned skal gjenspeile spesifikasjonens navn, f.eks. lik repo-navnet modelldcat-ap-no som også er i URLen på data.norge.no. Nå heter filen "document.pdf."

**Comment by stigbd** [comment]
Fiksa i 62fdb74 Er ute i "redaktørens utkast".
Fint om du kan verifisere før vi gjer det same i den offisielle versjonen på data.norge.no

**Comment by jimjyang** [comment]
> Fiksa i [62fdb74](https://github.com/Informasjonsforvaltning/modelldcat-ap-no/commit/62fdb7478912b083c78fe23a51354e45dc7b68de) Er ute i "redaktørens utkast".
> Fint om du kan verifisere før vi gjer det same i den offisielle versjonen på data.norge.no

Veldig bra!

**Comment by stigbd** [comment]
Har no også fiksa i offisiell versjon (v1).

**Comment by jimjyang** [comment]
> Har no også fiksa i offisiell versjon (v1).

Supert!

**Comment by jimjyang** [comment]
Det virker fint begge steder. Lukkes.
