### ISSUE TITLE
Publisering - "dokumentinfo" bør komme tidlig i PDF-filen som kan lastes ned

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/modelldcat-ap-no#352]
Det er ønskelig at "dokumentinfo" (status, versjonsnummer, publiserings- og oppdateringsdato etc.) kommer rett etter "forsiden" i PDF-versjonen som kan lastes ned. Nå er det den laaange innholdsfortegnelsen som kommer først i PDF-filen.

**Comment by ToHelland** [comment]
Det er opprettet et issue på dette, https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/182.
