### ISSUE TITLE
Modelltype (dct:type) - multiplisitet må utvides

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#360]
dct:type for klassen Informasjonsmodell (modelldcatno:InformationModel) har i dag multiplisitet 0..1. En modell kan være av flere typer, og multiplisiteten utvides derfor til 0..n.

Følgende må oppdateres:
Spesifikasjon
UML-modell
Shacl-fil må oppdateres.

**Comment by jimjyang** [comment]
Fiksa
