### ISSUE TITLE
Dokument (foaf:Document) - ny egenskap 

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#362]
Egenskap Dokument: har referanse (dct:seeAlso).
Range: rdfs:Resource
Multiplisitet 0..n

Dette for at det skal være mulig å referere til et dokument.
Følgende må oppdateres:
- OWL
- Spesifikasjon
- UML-modell 
- Shacl-fil

**Comment by jimjyang** [comment]
Fiksa
