### ISSUE TITLE
Kontaktopplysning (vcard:Kind)

### ISSUE THREAD

**Issue by JALinnerud** [Informasjonsforvaltning/modelldcat-ap-no#407]
For begreper og datasett i felles datakatalog står det 
•	Vi anbefaler sterkt å bruke organisatoriske enheter og ikke enkeltpersoner som kontaktpunkt. 
Hvorfor oppmuntres det da i modelldcat-ap-no å bruke vcard for kontaktopplysning med beskrivelsen
"Brukes til å representere en beskrivelse av en kontaktopplysning i henhold til vCard-spesifikasjonen. Her kan man for eksempel oppgi telefonnr og/eller epost. Merk at beskrivelsen må være en instans av en av fire typer: individ, organisasjon, lokasjon eller gruppe."
Anbefaler bedre konsistens. 
Uansett viser FDK brukergrensesnitt "Kontaktinformasjon" og ikke "Kontaktopplysning" for både begreper, datasett, APIer og informasjonsmodell.

**Comment by jimjyang** [comment]
Enig at vi ikke skal oppmuntre til personlige kontaktpunkter. 

**Forslag**: 
1. `vcard:Kind` byttes ut med `vcard:Organization`, og 
2. setningen "Merk at beskrivelsen må være en instans av en av fire typer: individ, organisasjon, lokasjon eller gruppe." strykes.

**Comment by jimjyang** [comment]
Fra diskusjonen på arbeidsgruppemøtet 9/6-21: 
1. range bør være `vcard:Organization or vcard:Group` slik at det er mulig å oppgi gruppe (i tillegg til en organisatorisk enhet) som kontaktpunkt.
2. Forklarende tekst bør si noe om at man om mulig bør bruke den organisatoriske enheten eller gruppen i virksomheten som har det funksjonelle ansvaret.
