### ISSUE TITLE
Beskrivelse i Attributt-klassen

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/modelldcat-ap-no#42]
Lagt inn tekst i beskrivelsesfeltet til Attributtklassen i word.

**Comment by tafjord** [comment]
fant ikke noen beskrivelse i Attributt-klassen i word..

**Comment by tafjord** [comment]
nope, kanskje jeg må lukke og åpne igjen?

**Comment by jimjyang** [comment]
Beskrivelsene er med nå, lukkes.
