### ISSUE TITLE
Klassen Egenskap - beskrivelser mangler

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/modelldcat-ap-no#72]
Fila (13_) er p.t. tom.

**Comment by tafjord** [comment]
hm. dette skjønner jeg ikke. skal vi se...

**Comment by tafjord** [comment]
nå har jeg en ny PR på den....

**Comment by tafjord** [comment]
https://github.com/Informasjonsforvaltning/modelldcat-ap-no/pull/77

**Comment by jimjyang** [comment]
Fiksa (#77)
