### ISSUE TITLE
Beskrive skillet mellom katalogdel og modelldel

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/modelldcat-ap-no#85]
vi har et skille mellom katalogdel og modelldel i spesifikasjonen som ikke er så godt forklart. @ToHelland kunne du lage en liten tekstsnutt med forklaring?

**Comment by tafjord** [comment]
Tror vi kan legge inn noen setninger i kap Omfang og avgrensninger. 

Et forslag, rediger gjerne @ToHelland @jimjyang (lagt inn i word også)

Vi har i spesifikasjonen valgt å skille mellom det vi kaller «katalogdel» og «modelldel». Hensikten er å gjøre det enklere å forstå hvilke klasser og egenskaper som brukes for å beskrive metadata knyttet til katalogoppføringen av informasjonsmodellen, og hvilke klasser og egenskaper som brukes for å beskrive/vise selve informasjonsmodellen.

**Comment by jimjyang** [comment]
Fiksa (#96)
