### ISSUE TITLE
Få frem at modelldcatno# uri ikke er operativ

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/modelldcat-ap-no#86]
Hvor skal vi forklare det? legge inn kommentar i tabellen?

**Comment by jimjyang** [comment]
Som kommentert under #92, har jeg i [DQV-AP-NO](https://informasjonsforvaltning.github.io/dqv-ap-no/) nevnt ontologien innledningsvis, og den kommer kommer på endelig URL.

**Comment by jimjyang** [comment]
Fiksa (#97)
