### ISSUE TITLE
owl-en

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/modelldcat-ap-no#92]
Owlen er ikke nevnt i spesifikasjonen. Hvor tar vi med den og hvordan? Lenker inn i github?

**Comment by ToHelland** [comment]
> Owlen er ikke nevnt i spesifikasjonen. Hvor tar vi med den og hvordan? Lenker inn i github?

@tafjord Foreslår vi lenker inn i github.

**Comment by tafjord** [comment]
Ok, en sjekk med @tormodv om det er ok eller om det finnes en enda bedre måte å få vist det på? Og takk! Vi hadde ikke greid dette uten deg. https://informasjonsforvaltning.github.io/modelldcat-ap-no/

**Comment by jimjyang** [comment]
I [DQV-AP-NO](https://informasjonsforvaltning.github.io/dqv-ap-no/) (under gjeldende versjon) har jeg nevnt og pekt til Github (som utkast) og "annonsert" den endelige URLen også.

**Comment by tafjord** [comment]
Smart! Vi kan gjøre det slik vi og. Blir URLen noe sånt noe? https://data.norge.no/vocabulary/modelldcatno#

**Comment by jimjyang** [comment]
Jepp

**Comment by jimjyang** [comment]
Jeg legger inn.

**Comment by jimjyang** [comment]
Fiksa (#97)
