### ISSUE TITLE
Attributt mangler beskrivelser

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/modelldcat-ap-no#98]
https://informasjonsforvaltning.github.io/modelldcat-ap-no/#_attributt

**Comment by jimjyang** [comment]
Jeg fant i Word-filen, jeg føyer til.

**Comment by jimjyang** [comment]
Faktisk flere beskrivelser mangler. Jeg fyller på.

**Comment by tafjord** [comment]
Hm, av og til får jeg en følelse av at ting ikke er pusha ordentlig fra meg

**Comment by jimjyang** [comment]
Fiksa (#99)
